local assets = {
	fluent3d = {
		books = "rbxasset://.asphalt-epoch/fluent3d/books.png",
		fileFolder = "rbxasset://.asphalt-epoch/fluent3d/fileFolder.png",
		gear = "rbxasset://.asphalt-epoch/fluent3d/gear.png",
		hammer = "rbxasset://.asphalt-epoch/fluent3d/hammer.png",
		magnifyingGlassTiltedRight = "rbxasset://.asphalt-epoch/fluent3d/magnifyingGlassTiltedRight.png",
		toolbox = "rbxasset://.asphalt-epoch/fluent3d/toolbox.png",
	},
}

return assets